version: "3.5"
services:
  jekyll:
    container_name: dstack-cnrdocks
    restart: always
    hostname: localhost
    build:
      context: ./
    ports:
      - 4000:4000
    volumes:
      - ..:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H localhost -t
